public_html/frontend/controllers/ReservasController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\Reservas;
use frontend\models\ReservasSearch;
use common\models\LoginForm;
use common\models\User;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;


/**
 * ReservasController implements the CRUD actions for Reservas model.
 */
class ReservasController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Reservas models.
     * @return mixed
     */
/*    
    public function actionIndex()
    {
        $searchModel = new ReservasSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
*/

    public function actionServicios()
    {
        $searchModel = new ReservasSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionIndex()
    {

        $modeluser = new User();
        $modeluser = User::findOne(Yii::$app->user->id);

        $model = new Reservas();
        $searchModel = new ReservasSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        
        if (isset($modeluser)){
            $username =  $modeluser->username; 

            if ($username =="administrador"){
                return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
                ]);
            }
        }

        return $this->render('calcular', [
            'model' => $model,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionPaginacalcular()
    {
        $model = new Reservas();
        $searchModel = new ReservasSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('calcular', [
            'model' => $model,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

/*BASIC
        public function actionIndex()
    {
        $model = new Reservas();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_reserva]);
        }

        return $this->render('calcular', [
            'model' => $model,
        ]);
    } 
*/


    public function actionCalcular()
    {

    //ReservasController::actionCalcular()

    //require __DIR__  .'/'.'../index.php';


    //require __DIR__  .'/'.'../vendor/mercadopago/dxphp/src/MercadoPago/SDK.php';
    //require __DIR__  .'/../vendor/autoload.php';
    //require_once Yii::$app->basePath.'/vendor/autoload.php';


/*
    require_once '../vendor/autoload.php';

    MercadoPago\SDK::setAccessToken("TEST-6826639623857597-052419-a94c61726060ad11a6dbbf8266430046-321582894");

    $payment = new MercadoPago\Payment();

    $payment->transaction_amount = 141;
    $payment->token = "YOUR_CARD_TOKEN";
    $payment->description = "Ergonomic Silk Shirt";
    $payment->installments = 1;
    $payment->payment_method_id = "visa";
    $payment->payer = array(
      "email" => "larue.nienow@hotmail.com"
    );

    $payment->save();

    echo $payment->status;
*/

    $session = Yii::$app->session;



    $model = new Reservas();

    $request = Yii::$app->request;

    // devuelve todos los parámetros
    $params = $request->bodyParams;

    //$dni = $params['Reservas']['dni']; 
    $cantidad_habitaciones = $params['Reservas']['cantidad_habitaciones'];
    $cantidad_banos = $params['Reservas']['cantidad_banos'];
    $fecha_desde = $params['Reservas']['fecha_desde'];
    $fecha_hasta = $params['Reservas']['fecha_hasta'];


    $session['cantidad_habitaciones'] = $cantidad_habitaciones;
    $session['cantidad_banos'] = $cantidad_banos;
    $session['fecha_desde'] = $fecha_desde;
    $session['fecha_hasta'] = $fecha_hasta;

/*
    $datetime1  = date_create($fecha_desde);
    $datetime1  = date_create(date_format($datetime1 , 'Y-m-d'));
    $datetime2  = date_create($fecha_hasta);
    $datetime2  = date_create(date_format($datetime2  , 'Y-m-d'));    
    $interval   = date_diff($datetime1, $datetime2);
    $numero_dias = $interval->format('%a');
    $numero_dias = $numero_dias * 1;

*/
    $datetime1  = date_create($fecha_desde);
    $datetime1  = date_create(date_format($datetime1 , 'Y-m-d'));
    $datetime2  = date_create($fecha_hasta);
    $datetime2  = date_create(date_format($datetime2  , 'Y-m-d'));    
    $interval   = date_diff($datetime1, $datetime2);
    $numero_dias = $interval->format('%R%a');

//echo $numero_dias; exit;

    //$numero_dias = $numero_dias * 1;



//echo $numero_dias; exit;


    if ($numero_dias < 0){

            Yii::$app->session->setFlash('error', "La Fecha Hasta no puede ser menor a la Fecha Desde");
            return $this->redirect(['index']);
    }    
    elseif ($numero_dias <= 5){

        $base_servicio=15;
        $costo_habitacion=2.5;
        $costo_bano=2.5;
        $costo_total= $base_servicio+($numero_dias*($cantidad_habitaciones*$costo_habitacion))+($numero_dias*($cantidad_banos*$costo_bano));
        $variable="menos de 5 dias, se quedara: ".$numero_dias ." dias "." por un precio total de: ".$costo_total." $";
    }
    elseif ($numero_dias <= 10){

        $base_servicio=20;
        $costo_habitacion=4;
        $costo_bano=4;
        $costo_total= $base_servicio+($numero_dias*($cantidad_habitaciones*$costo_habitacion))+($numero_dias*($cantidad_banos*$costo_bano));        
        $variable="mas de 5 pero menos de 10 dias, se quedara: ".$numero_dias ." dias "." por un precio total de: ".$costo_total." $";

    }
    elseif($numero_dias > 10){

        $base_servicio=30;
        $costo_habitacion=5;
        $costo_bano=5;
        $costo_total= $base_servicio+($numero_dias*($cantidad_habitaciones*$costo_habitacion))+($numero_dias*($cantidad_banos*$costo_bano));        
        $variable="mas de 10 dias, se quedara: ".$numero_dias ." dias "." por un precio total de: ".$costo_total." $";
    }
 




        $parametros_array=array(
            'model' => $model,
            'base_servicio' => $base_servicio,
            'costo_habitacion' => $costo_habitacion, 
            'costo_bano' => $costo_bano,
            'costo_total' => $costo_total,
            'numero_dias' => $numero_dias, 
            'variable' => $variable,  
            'cantidad_habitaciones' => $cantidad_habitaciones,
            'cantidad_banos' => $cantidad_banos,                                                
            'fecha_desde' => $fecha_desde, 
            'fecha_hasta' => $fecha_hasta,             
        ); 



       //Yii::$app->view->renderFile('@app/views/reservas/servicio_calculado.php',array('variable' => $variable,),false,true);

        return $this->render('@app/views/reservas/servicio_calculado.php', $parametros_array);




/*
        $model = new Reservas();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_reserva]);
        }
*/        
        //$variable = " Calculado "." cantidad de habitaciones ".$ch." cantidad de baños ".$cb. "DIAS ".$total_dias;
        
        //return $variable;
    }


    public function actionVerificacion()
    {

    $model = new LoginForm();
    $modeluser = new User();


    if (!Yii::$app->user->isGuest) {

            // devuelve todos los parámetros
            $request = Yii::$app->request;
            $params = $request->bodyParams;

            $modeluser = User::findOne(Yii::$app->user->id);

            $dni =  $modeluser->dni;
            $costo_total = $params['Reservas']['costo_total'];
            $numero_dias = $params['Reservas']['numero_dias'];    
            $cantidad_habitaciones = $params['Reservas']['cantidad_habitaciones'];
            $cantidad_banos = $params['Reservas']['cantidad_banos'];
            $fecha_desde = $params['Reservas']['fecha_desde'];
            $fecha_hasta = $params['Reservas']['fecha_hasta']; 
            $status = "Check in";    

                $data=array(
                    'dni' => $dni,
                    'costo_total' => $costo_total,
                    'numero_dias' => $numero_dias, 
                    'cantidad_habitaciones' => $cantidad_habitaciones,
                    'cantidad_banos' => $cantidad_banos,                                                
                    "fecha_desde" => $fecha_desde, 
                    "fecha_hasta" => $fecha_hasta, 
                    "estatus" => $status,         
                ); 
            ReservasController::actionGuardar($data);
    }
    else{
        
        return $this->redirect(['site/login']);

       //SiteController::actionLogin(); 

        //return $this->render('@app/views/site/login.php', $data);           
    }


    }

    public function actionGuardar($data)
    {
        $model = new Reservas();


        $fechaactual = getdate();
        $fecha_reserva ="$fechaactual[year]"."-"."$fechaactual[mon]"."-"."$fechaactual[mday]";


        $model->dni = $data['dni'];
        $model->cantidad_habitaciones = $data['cantidad_habitaciones'];
        $model->cantidad_banos = $data['cantidad_banos']; 
        $model->fecha_reserva =  $fecha_reserva;  
        $model->fecha_desde =  $data['fecha_desde']; 

public_html/frontend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<!--
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
-->
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        //'brandLabel' => Yii::$app->name,
        'brandLabel' => 'Handi',        
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => 'Inicio', 'url' => ['/site/index']],
        //['label' => 'Sobre Nosotros', 'url' => ['/site/about']],
        ['label' => 'Contacto', 'url' => ['/site/contact']],
    ];
    if (!Yii::$app->user->isGuest) {
        //$menuItems[] = ['label' => 'Regístrate', 'url' => ['/site/signup']];
        $menuItems[] = ['label' => 'Reservas', 'url' => ['/reservas/servicios']];
    }    
    if (Yii::$app->user->isGuest) {
        //$menuItems[] = ['label' => 'Regístrate', 'url' => ['/site/signup']];
        $menuItems[] = ['label' => 'Iniciar sesión', 'url' => ['/site/login']];
    } else {
        $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Cerrar Sesión (' . Yii::$app->user->identity->username . ')',
                ['class' => 'btn btn-link logout']
            )
            . Html::endForm()
            . '</li>';
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; <?= Html::encode(Yii::$app->name) ?> <?= date('Y') ?></p>

        <p class="pull-right"><?php //echo "Desarrollado por Kailer Udiz"//Yii::powered() ?>

          <a href="#"><i class="fa fa-facebook-official"></i></a>
          <a href="#"><i class="fa fa-twitter"></i></a>
          <a href="#"><i class="fa fa-linkedin"></i></a>
        </p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>