public_html/frontend/models/Reservas.php
<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "reservas".
 *
 * @property int $id_reserva
 * @property int $dni
 * @property int $cantidad_habitaciones
 * @property int $cantidad_banos
 * @property string $fecha_reserva
 * @property string $fecha_desde
 * @property string $fecha_hasta
 * @property int $numero_dias
 * @property string $estatus
 * @property double $costo_total
 *
 * @property User $dni0
 */
class Reservas extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'reservas';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['dni', 'cantidad_habitaciones', 'cantidad_banos', 'fecha_reserva', 'fecha_desde', 'fecha_hasta', 'numero_dias'], 'required'],
            [['dni', 'cantidad_habitaciones', 'cantidad_banos', 'numero_dias'], 'default', 'value' => null],
            [['dni', 'cantidad_habitaciones', 'cantidad_banos', 'numero_dias'], 'integer'],
            [['fecha_reserva', 'fecha_desde', 'fecha_hasta'], 'safe'],
            [['estatus'], 'string'],
            [['costo_total'], 'number'],          
            //[['dni'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['dni' => 'dni']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_reserva' => 'Id Reserva',
            'dni' => 'Dni',
            'cantidad_habitaciones' => 'Cantidad Habitaciones',
            'cantidad_banos' => 'Cantidad Banos',
            'fecha_reserva' => 'Fecha Reserva',
            'fecha_desde' => 'No se aceptan reservas con menos de 48 horas - Fecha Desde',
            'fecha_hasta' => 'No se aceptan reservas con menos de 48 horas - Fecha Hasta',
            'numero_dias' => 'Numero Dias',
            'estatus' => 'Estatus',
            'costo_total' => 'Costo Total',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDni0()
    {
        return $this->hasOne(User::className(), ['dni' => 'dni']);
    }
}

public_html/frontend/controllers/ReservasController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\Reservas;
use frontend\models\ReservasSearch;
use common\models\LoginForm;
use common\models\User;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;


/**
 * ReservasController implements the CRUD actions for Reservas model.
 */
class ReservasController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Reservas models.
     * @return mixed
     */
/*    
    public function actionIndex()
    {
        $searchModel = new ReservasSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
*/

    public function actionServicios()
    {
        $searchModel = new ReservasSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionIndex()
    {

        $modeluser = new User();
        $modeluser = User::findOne(Yii::$app->user->id);

        $model = new Reservas();
        $searchModel = new ReservasSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        
        if (isset($modeluser)){
            $username =  $modeluser->username; 

            if ($username =="administrador"){
                return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
                ]);
            }
        }

        return $this->render('calcular', [
            'model' => $model,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionPaginacalcular()
    {
        $model = new Reservas();
        $searchModel = new ReservasSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('calcular', [
            'model' => $model,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

/*BASIC
        public function actionIndex()
    {
        $model = new Reservas();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_reserva]);
        }

        return $this->render('calcular', [
            'model' => $model,
        ]);
    } 
*/


    public function actionCalcular()
    {

    //ReservasController::actionCalcular()

    //require __DIR__  .'/'.'../index.php';


    //require __DIR__  .'/'.'../vendor/mercadopago/dxphp/src/MercadoPago/SDK.php';
    //require __DIR__  .'/../vendor/autoload.php';
    //require_once Yii::$app->basePath.'/vendor/autoload.php';


/*
    require_once '../vendor/autoload.php';

    MercadoPago\SDK::setAccessToken("TEST-6826639623857597-052419-a94c61726060ad11a6dbbf8266430046-321582894");

    $payment = new MercadoPago\Payment();

    $payment->transaction_amount = 141;
    $payment->token = "YOUR_CARD_TOKEN";
    $payment->description = "Ergonomic Silk Shirt";
    $payment->installments = 1;
    $payment->payment_method_id = "visa";
    $payment->payer = array(
      "email" => "larue.nienow@hotmail.com"
    );

    $payment->save();

    echo $payment->status;
*/

    $session = Yii::$app->session;



    $model = new Reservas();

    $request = Yii::$app->request;

    // devuelve todos los parámetros
    $params = $request->bodyParams;

    //$dni = $params['Reservas']['dni']; 
    $cantidad_habitaciones = $params['Reservas']['cantidad_habitaciones'];
    $cantidad_banos = $params['Reservas']['cantidad_banos'];
    $fecha_desde = $params['Reservas']['fecha_desde'];
    $fecha_hasta = $params['Reservas']['fecha_hasta'];


    $session['cantidad_habitaciones'] = $cantidad_habitaciones;
    $session['cantidad_banos'] = $cantidad_banos;
    $session['fecha_desde'] = $fecha_desde;
    $session['fecha_hasta'] = $fecha_hasta;

/*
    $datetime1  = date_create($fecha_desde);
    $datetime1  = date_create(date_format($datetime1 , 'Y-m-d'));
    $datetime2  = date_create($fecha_hasta);
    $datetime2  = date_create(date_format($datetime2  , 'Y-m-d'));    
    $interval   = date_diff($datetime1, $datetime2);
    $numero_dias = $interval->format('%a');
    $numero_dias = $numero_dias * 1;

*/
    $datetime1  = date_create($fecha_desde);
    $datetime1  = date_create(date_format($datetime1 , 'Y-m-d'));
    $datetime2  = date_create($fecha_hasta);
    $datetime2  = date_create(date_format($datetime2  , 'Y-m-d'));    
    $interval   = date_diff($datetime1, $datetime2);
    $numero_dias = $interval->format('%R%a');

//echo $numero_dias; exit;

    //$numero_dias = $numero_dias * 1;



//echo $numero_dias; exit;


    if ($numero_dias < 0){

            Yii::$app->session->setFlash('error', "La Fecha Hasta no puede ser menor a la Fecha Desde");
            return $this->redirect(['index']);
    }    
    elseif ($numero_dias <= 5){

        $base_servicio=15;
        $costo_habitacion=2.5;
        $costo_bano=2.5;
        $costo_total= $base_servicio+($numero_dias*($cantidad_habitaciones*$costo_habitacion))+($numero_dias*($cantidad_banos*$costo_bano));
        $variable="menos de 5 dias, se quedara: ".$numero_dias ." dias "." por un precio total de: ".$costo_total." $";
    }
    elseif ($numero_dias <= 10){

        $base_servicio=20;
        $costo_habitacion=4;
        $costo_bano=4;
        $costo_total= $base_servicio+($numero_dias*($cantidad_habitaciones*$costo_habitacion))+($numero_dias*($cantidad_banos*$costo_bano));        
        $variable="mas de 5 pero menos de 10 dias, se quedara: ".$numero_dias ." dias "." por un precio total de: ".$costo_total." $";

    }
    elseif($numero_dias > 10){

        $base_servicio=30;
        $costo_habitacion=5;
        $costo_bano=5;
        $costo_total= $base_servicio+($numero_dias*($cantidad_habitaciones*$costo_habitacion))+($numero_dias*($cantidad_banos*$costo_bano));        
        $variable="mas de 10 dias, se quedara: ".$numero_dias ." dias "." por un precio total de: ".$costo_total." $";
    }
 




        $parametros_array=array(
            'model' => $model,
            'base_servicio' => $base_servicio,
            'costo_habitacion' => $costo_habitacion, 
            'costo_bano' => $costo_bano,
            'costo_total' => $costo_total,
            'numero_dias' => $numero_dias, 
            'variable' => $variable,  
            'cantidad_habitaciones' => $cantidad_habitaciones,
            'cantidad_banos' => $cantidad_banos,                                                
            'fecha_desde' => $fecha_desde, 
            'fecha_hasta' => $fecha_hasta,             
        ); 



       //Yii::$app->view->renderFile('@app/views/reservas/servicio_calculado.php',array('variable' => $variable,),false,true);

        return $this->render('@app/views/reservas/servicio_calculado.php', $parametros_array);




/*
        $model = new Reservas();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_reserva]);
        }
*/        
        //$variable = " Calculado "." cantidad de habitaciones ".$ch." cantidad de baños ".$cb. "DIAS ".$total_dias;
        
        //return $variable;
    }


    public function actionVerificacion()
    {

    $model = new LoginForm();
    $modeluser = new User();


    if (!Yii::$app->user->isGuest) {

            // devuelve todos los parámetros
            $request = Yii::$app->request;
            $params = $request->bodyParams;

            $modeluser = User::findOne(Yii::$app->user->id);

            $dni =  $modeluser->dni;
            $costo_total = $params['Reservas']['costo_total'];
            $numero_dias = $params['Reservas']['numero_dias'];    
            $cantidad_habitaciones = $params['Reservas']['cantidad_habitaciones'];
            $cantidad_banos = $params['Reservas']['cantidad_banos'];
            $fecha_desde = $params['Reservas']['fecha_desde'];
            $fecha_hasta = $params['Reservas']['fecha_hasta']; 
            $status = "Check in";    

                $data=array(
                    'dni' => $dni,
                    'costo_total' => $costo_total,
                    'numero_dias' => $numero_dias, 
                    'cantidad_habitaciones' => $cantidad_habitaciones,
                    'cantidad_banos' => $cantidad_banos,                                                
                    "fecha_desde" => $fecha_desde, 
                    "fecha_hasta" => $fecha_hasta, 
                    "estatus" => $status,         
                ); 
            ReservasController::actionGuardar($data);
    }
    else{
        
        return $this->redirect(['site/login']);

       //SiteController::actionLogin(); 

        //return $this->render('@app/views/site/login.php', $data);           
    }


    }

    public function actionGuardar($data)
    {
        $model = new Reservas();


        $fechaactual = getdate();
        $fecha_reserva ="$fechaactual[year]"."-"."$fechaactual[mon]"."-"."$fechaactual[mday]";


        $model->dni = $data['dni'];
        $model->cantidad_habitaciones = $data['cantidad_habitaciones'];
        $model->cantidad_banos = $data['cantidad_banos']; 
        $model->fecha_reserva =  $fecha_reserva;  
        $model->fecha_desde =  $data['fecha_desde']; 

public_html/frontend/views/reservas/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\Reservas */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="reservas-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'dni')->textInput() ?>

    <?= $form->field($model, 'cantidad_habitaciones')->textInput() ?>

    <?= $form->field($model, 'cantidad_banos')->textInput() ?>

    <?= $form->field($model, 'fecha_reserva')->textInput() ?>

    <?= $form->field($model, 'fecha_desde')->textInput() ?>

    <?= $form->field($model, 'fecha_hasta')->textInput() ?>

    <?= $form->field($model, 'numero_dias')->textInput() ?>

    <?= $form->field($model, 'costo_total')->textInput() ?>

    <?= $form->field($model, 'estatus')->textInput() ?>    

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

public_html/frontend/views/reservas/_formestatus.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\Reservas */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="reservas-form">

    <?php $form = ActiveForm::begin(); ?>

    <!--$form->field($model, 'estatus')->textInput()--> 

 

    <?= $form->field($model, 'estatus')->dropDownList(['Check in' => 'Check in', 'Pago Confirmado' => 'Pago Confirmado', 'Recogida de llaves' => 'Recogida de llaves', 'Limpieza' => 'Limpieza', 'Fin del Servicio' => 'Fin del Servicio'], ['options'=>['Check in'=>['Selected'=>true]]])?>    

    <div class="form-group">
        <?= Html::submitButton('Actualizar Estatus', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

public_html/frontend/views/reservas/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\ReservasSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="reservas-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id_reserva') ?>

    <?= $form->field($model, 'dni') ?>

    <?= $form->field($model, 'cantidad_habitaciones') ?>

    <?= $form->field($model, 'cantidad_banos') ?>

    <?= $form->field($model, 'fecha_reserva') ?>

    <?php // echo $form->field($model, 'fecha_desde') ?>

    <?php // echo $form->field($model, 'fecha_hasta') ?>

    <?php // echo $form->field($model, 'numero_dias') ?>

    <?php // echo $form->field($model, 'costo_total') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

public_html/frontend/views/reservas/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model frontend\models\Reservas */

$this->title = 'Create Reservas';
$this->params['breadcrumbs'][] = ['label' => 'Reservas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="reservas-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

public_html/frontend/views/reservas/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

use yii\bootstrap\Modal;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel frontend\models\ReservasSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Reservas';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="reservas-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Crear Reservas', ['paginacalcular'], ['class' => 'btn btn-success']) ?>

        <?php //Html::button('Create Reservas', ['id' => 'modelButton', 'value' => \yii\helpers\Url::to(['reservas/create']), 'class' => 'btn btn-success']) ?>
    </p>

    <?php 
    /*
        Modal::begin([
                'header' => '',
                'id'     => 'model',
                'size'   => 'model-lg',
        ]);
        
        echo "<div id='modelContent'></div>";
        
        Modal::end();
    */      
    ?>  

    <?php
        Modal::begin([
                'header'=>'<h4>Gererando Botón de Pago...</h4>',
                'id'=>'pagar-modal',
                'size'=>'modal-lg'
        ]);

        echo "<div id='pagarModalContent'></div>";

        Modal::end();
    ?> 

    <?php
        Modal::begin([
                'header'=>'<h1>Estatus del Servicio</h1>',
                'id'=>'view-modal',
                'size'=>'modal-lg'
        ]);

        echo "<div id='viewModalContent'></div>";

        Modal::end();
    ?>  

<div class="table-responsive">
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id_reserva',
            'dni',
            'cantidad_habitaciones',
            'cantidad_banos',
            'fecha_reserva',
            //'fecha_desde',
            //'fecha_hasta',
            //'numero_dias',
            'costo_total',
            'estatus',            

            //['class' => 'yii\grid\ActionColumn'],


            /*
            ['class' => 'yii\grid\ActionColumn',
            'template' => '{view} {update} {delete} {link} {pagar} {leadDelete}',
            'buttons' => [
                
                'update' => function ($url,$model) {
                    return Html::a(
                        '<span class="glyphicon glyphicon-user"></span>', 
                        $url);
                },
                'link' => function ($url,$model,$key) {
                    return Html::a('Action', $url);
                },
                
                'pagar' => function ($url,$model) {
                    return Html::a(
                        '<span class="text-success glyphicon glyphicon-ok" id="modelButton" title="Enviar Pago"></span>', 
                        $url);
                },  

                'leadDelete' => function ($url, $model) {
                    $url = Url::to(['reservas/pagar', 'id' => $model->id_reserva]);
                    return Html::a('<span class="glyphicon glyphicon-ok"></span>', $url, [
                        'title'        => 'create',
                        //'data-confirm' => Yii::t('yii', 'Are you sure you want to delete this item?'),
                        'data-method'  => 'post',
                    ]);
                }, 

            ],],
            */

            [
                'class' => 'yii\grid\ActionColumn',
                'options'=>['class'=>'action-column'],
                'template'=>'{view} {pagar}',
                'buttons'=>[
/*
                            'view' => function ($url,$model) {
                                return Html::a(
                                    '<span class="glyphicon glyphicon-search" title="Ver"></span>', 
                                    $url);
                            }, 
*/
                            'view' => function($url,$model,$key){
                                $btn1 = Html::button("<span class='text-primary glyphicon glyphicon-search'></span>",[
                                    'value'=>Yii::$app->urlManager->createUrl('reservas/viewreserva?id='.$model->id_reserva), //<---- here is where you define the action that handles the ajax request
                                    'class'=>'view-modal-click grid-action',
                                    'data-toggle'=>'tooltip',
                                    'data-placement'=>'bottom',
                                    'title'=>'Ver'
                                ]);
                            return $btn1;                              
                            },
                            'pagar' => function($url,$model,$key){
                                $btn1 = Html::button("<span class='text-success glyphicon glyphicon-ok'></span>",[
                                    'value'=>Yii::$app->urlManager->createUrl('reservas/pagar?id='.$model->id_reserva), //<---- here is where you define the action that handles the ajax request
                                    'class'=>'pagar-modal-click grid-action',
                                    'data-toggle'=>'tooltip',
                                    'data-placement'=>'bottom',
                                    'title'=>'Pagar'
                                ]);
                            return $btn1;
                            }
                ]
            ],            



        ],
    ]); ?>
</div>    
</div>

public_html/frontend/views/reservas/servicio_calculado.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

use yii\helpers\Url;

use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\Reservas */
/* @var $form yii\widgets\ActiveForm */


$this->title = 'Calcula tu Reserva';
$this->params['breadcrumbs'][] = ['label' => 'Reservas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;



            echo " Total dias= ".$numero_dias." --- "; 
            echo "Base del servicio= ".$base_servicio." --- ";
            echo " Costo de la habitación= ".$costo_habitacion." --- "; 
            echo " Costo de la habitación= ".$costo_bano." --- ";
            echo " Precio Total= ".$costo_total." --- ";
            echo $variable;


?>

<div class="reservas-form">

 
     <h1>Su Calculo de servicio es:</h1> 
  
    <?php $form = ActiveForm::begin(['id' => 'login-form','options' => ['class' => 'form-horizontal'],'action' => Url::to(['/reservas/verificacion']), ]) ?> 

    <?= $form->field($model, 'cantidad_habitaciones')->hiddenInput(['value'=>$cantidad_habitaciones])->label(false); ?>
    <?= $form->field($model, 'cantidad_banos')->hiddenInput(['value'=>$cantidad_banos])->label(false); ?>
    <?= $form->field($model, 'numero_dias')->hiddenInput(['value'=>$numero_dias])->label(false); ?>
    <?= $form->field($model, 'costo_total')->hiddenInput(['value'=>$costo_total])->label(false); ?> 
    <?= $form->field($model, 'fecha_desde')->hiddenInput(['value'=>$fecha_desde])->label(false); ?> 
    <?= $form->field($model, 'fecha_hasta')->hiddenInput(['value'=>$fecha_hasta])->label(false); ?>            


    <div class="form-group row">
        <div class="input-group col-xs-offset-7 col-xs-4 col-sm-3 col-md-3">
              <span class="input-group-addon">$</span>
              <input type="text" class="form-control input-lg" value=<?php echo $costo_total; ?> align="right" disabled>
              <!--<span class="input-group-addon">.00</span>-->
        </div>
    </div><br>



    <div class="form-group">
        <div class="text-center">        
          <?= Html::submitButton('Reservar', ['class' => 'btn btn-success']) ?>
        </div>            
    </div>

    <?php ActiveForm::end(); ?>
 
</div>

public_html/frontend/views/reservas/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\Reservas */

$this->title = 'Update Reservas: ' . $model->id_reserva;
$this->params['breadcrumbs'][] = ['label' => 'Reservas', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id_reserva, 'url' => ['view', 'id' => $model->id_reserva]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="reservas-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

public_html/frontend/views/reservas/updatestatus.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\Reservas */

$this->title = 'Actualizar Reserva: ' . $model->id_reserva;
$this->params['breadcrumbs'][] = ['label' => 'Reservas', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id_reserva, 'url' => ['view', 'id' => $model->id_reserva]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="reservas-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_formestatus', [
        'model' => $model,
    ]) ?>

</div>

public_html/frontend/views/reservas/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

use common\models\User;

//$this->registerCssFile("@frontend/web/css/style.css");

/* @var $this yii\web\View */
/* @var $model frontend\models\Reservas */

//$this->title = $model->id_reserva;
$this->params['breadcrumbs'][] = ['label' => 'Reservas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="checkout-wrap">
  <ul class="checkout-bar">
        <?php if ($model->estatus=="Check in"){ ?>
            <li class="active">Check in</a></li>    
            <li class="next">Pago Confirmado</li>    
            <li class="next">Recogida de llaves</li>    
            <li class="next">Limpieza</li>    
            <li class="next">Fin del Servicio</li>
        <?php }elseif ($model->estatus=="Pago Confirmado"){ ?>
            <li class="previous visited">Check in</a></li>    
            <li class="active">Pago Confirmado</li>    
            <li class="next">Recogida de llaves</li>    
            <li class="next">Limpieza</li>    
            <li class="next">Fin del Servicio</li> 
        <?php }elseif ($model->estatus=="Recogida de llaves"){ ?> 
            <li class="previous visited">Check in</a></li>    
            <li class="previous visited">Pago Confirmado</li>    
            <li class="active">Recogida de llaves</li>    
            <li class="next">Limpieza</li>    
            <li class="next">Fin del Servicio</li> 
        <?php }elseif ($model->estatus=="Limpieza"){ ?> 
            <li class="previous visited">Check in</a></li>    
            <li class="previous visited">Pago Confirmado</li>    
            <li class="previous visited">Recogida de llaves</li>    
            <li class="active">Limpieza</li>    
            <li class="next">Fin del Servicio</li>
        <?php }elseif ($model->estatus=="Fin del Servicio"){ ?> 
            <li class="previous visited">Check in</a></li>    
            <li class="previous visited">Pago Confirmado</li>    
            <li class="previous visited">Recogida de llaves</li>    
            <li class="previous visited">Limpieza</li>    
            <li class="active">Fin del Servicio</li>
        <?php } ?>                                                                                      
  </ul>
</div>

<br><br><br><br><br><br><br>

<div class="reservas-view">

<h1><?= Html::encode($this->title) ?></h1>

<?php
        $modeluser = new User();
        $modeluser = User::findOne(Yii::$app->user->id);

        if (isset($modeluser)){
            $username =  $modeluser->username; 

            if ($username =="administrador"){ ?>
                <?= Html::a('Actualizar Estatus', ['update', 'id' => $model->id_reserva], ['class' => 'btn btn-primary']) ?> <?php
            }
        }   
?>

<!--
    <p>
         Html::a('Update', ['update', 'id' => $model->id_reserva], ['class' => 'btn btn-primary']) ?>
         Html::a('Delete', ['delete', 'id' => $model->id_reserva], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>
-->
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id_reserva',
            'dni',
            'cantidad_habitaciones',
            'cantidad_banos',
            'fecha_reserva',
            'fecha_desde',
            'fecha_hasta',
            'numero_dias',
            'costo_total',
            'estatus',
        ],
    ]) ?>

</div>